spring:
  application:
    name: weather

  datasource:
    url: jdbc:mysql://localhost:3306/weather_diary?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssongha1984!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.jdbc.time_zone: Asia/Seoul

openweather:
  base-url: https://api.openweathermap.org/data/2.5
  city: Seoul
  api-key: ${OPENWEATHER_API_KEY:PUT-YOUR-KEY}
